#!C:\Users\KR\Desktop\python_work\FASTAPI\fvenv\Scripts\python.exe
import sys
# import the code from this package
from shell_command_logger.recorder import main_recorder

if __name__ == "__main__":
    command = sys.argv[1:]
    exit_code = main_recorder(command, __file__)
    sys.exit(exit_code)

